image:
  file: .gitpod/Dockerfile
ports:
  - port: 8085
tasks:
  - init: dotnet tool install fake-cli -g && dotnet tool install paket -g && export PATH=~/.dotnet/tools:$PATH
    command: fake build -t Run

vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==