image:
  file: .gitpod/Dockerfile
ports:
  - port: 8085
tasks:
  - command: export PATH=~/.dotnet/tools:$PATH && fake build -t Run

vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==