image:
  file: .gitpod/Dockerfile
ports:
  - port: 8085
tasks:
  - init: dotnet tool install fake-cli -g
  - init: dotnet tool install paket -g
  - init: export PATH=~/.dotnet/tools:$PATH
vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.0.6:jY7uvWaRUfDGixUAwJWzOg==